- hosts: paz
  gather_facts: false
  tasks:
    - win_file:
        path: '{{ firefox_distribution_dir }}'
        state: directory
    - win_copy:
        src: policies.json
        dest: '{{ firefox_distribution_dir }}\policies.json'
