- name: Disable touchscreen
  hosts: paz
  gather_facts: false
  tasks:
    - name: Desabilitar tela touch
      ansible.windows.win_shell: |
        Get-PnpDevice | Where-Object { $_.FriendlyName -like '*touch screen*' } | Disable-PnpDevice -Confirm:$false
