- name: Enable touchscreen
  hosts: paz
  gather_facts: false
  tasks:
    - name: Habilitar tela touch
      ansible.windows.win_shell: |
        Get-PnpDevice | Where-Object { $_.FriendlyName -like '*touch screen*' } | Enable-PnpDevice -Confirm:$false
