- hosts: paz
  gather_facts: no
  tasks:
    - ansible.windows.win_stat:
        path: C:\Users\User\gcompris-qt-26.1-win64-gcc.exe
      register: gcompris_installer

    - ansible.builtin.fail:
        msg: Instalador local do GCompris nao encontrado em C:\Users\User\gcompris-qt-26.1-win64-gcc.exe.
      when: not gcompris_installer.stat.exists

    - ansible.windows.win_package:
        path: C:\Users\User\gcompris-qt-26.1-win64-gcc.exe
        arguments: /S
        state: present
      when: gcompris_installer.stat.exists
