- name: Install Lunati
  hosts: paz
  gather_facts: false
  vars:
    zip_name: 'luanti-5.15.1-win64'
    folder_name: 'Luanti'
    work_path: "luanti-5.15.1-win64/bin"
    exe_name: 'luanti'
    lnk_name: 'Luanti'

    local_zip_path: '/home/lucas/Downloads/{{ zip_name }}.zip'
    remote_zip_path: '{{ windows_temp_dir }}\{{ zip_name }}.zip'
    install_dir: '{{ desktop_dir }}\{{ folder_name }}'
    exe_path: '{{ install_dir }}\{{ work_path }}\{{ exe_name }}.exe'
    shortcut_path: '{{ desktop_dir }}\{{ lnk_name}}.lnk'

  tasks:
    - name: Verifica remoto
      ansible.windows.win_stat:
        path: '{{ exe_path }}'
      register: exe

    - name: Verifica arquivo local
      ansible.builtin.stat:
        path: '{{ local_path }}'
      register: local_file
      delegate_to: localhost

    - name: Falha se arquivo local nao encontrado
      ansible.builtin.fail:
        msg: Arquivo local nao encontrado em {{ local_zip_path }}.
      when: not local_file.stat.exists

    - name: Copia arquivo para maquina remota
      ansible.windows.win_copy:
        src: '{{ local_zip_path }}'
        dest: '{{ remote_zip_path }}'
      when: not exe.stat.exists

    - name: Extrai arquivo zip
      ansible.windows.win_shell: '& "{{ seven_zip_binary_path }}" x -o "{{ install_dir }}" "{{ remote_path }}"'
      args:
        creates: '{{ binary_path }}'
      when: not exe.stat.exists

    - name: Remove arquivo zip
      ansible.windows.win_file:
        path: '{{ remote_zip_path }}'
        state: absent
      when: not exe.stat.exists

    - name: Cria atalho na area de trabalho
      ansible.windows.win_shell: |
        $TargetFile = "{{ exe_path }}"
        $ShortcutFile = "{{ shortcut_path }}"
        $Path = "{{ install_dir }}\{{ work_path }}"
        $WScriptShell = New-Object -ComObject WScript.Shell
        $Shortcut = $WScriptShell.CreateShortcut($ShortcutFile)
        $Shortcut.TargetPath = $TargetFile
        $Shortcut.WorkingDirectory = $Path
        $Shortcut.Save()
      args:
        creates: '{{ shortcut_path }}'
