- name: Install GCompris
  hosts: paz
  gather_facts: false
  tasks:
    - name: Baixar instalador do GCompris
      ansible.windows.win_get_url:
        url: '{{ gcompris_installer_url }}'
        dest: '{{ gcompris_installer_path }}'

    - name: Instalar GCompris
      ansible.windows.win_package:
        path: '{{ gcompris_installer_path }}'
        state: present

    - name: Remover instalador do GCompris
      ansible.windows.win_file:
        path: '{{ gcompris_installer_path }}'
        state: absent
