- hosts: paz
  gather_facts: no
  tasks:
    - ansible.windows.win_stat:
        path: '{{ seven_zip_binary_path }}'
      register: seven_zip_binary

    - ansible.builtin.fail:
        msg: 7-Zip nao encontrado em {{ seven_zip_binary_path }}.
      when: not seven_zip_binary.stat.exists

    - ansible.windows.win_stat:
        path: '{{ ktuberling_binary_path }}'
      register: ktuberling_binary

    - ansible.windows.win_get_url:
        url: '{{ ktuberling_archive_url }}'
        dest: '{{ ktuberling_archive_path }}'
      when: not ktuberling_binary.stat.exists

    - ansible.windows.win_file:
        path: '{{ ktuberling_install_dir }}'
        state: directory
      when: not ktuberling_binary.stat.exists

    - ansible.windows.win_command: >-
        {{ seven_zip_binary_path }}
        x
        -aoa
        -o{{ ktuberling_install_dir }}
        {{ ktuberling_archive_path }}
      args:
        creates: '{{ ktuberling_binary_path }}'
      when: not ktuberling_binary.stat.exists

    - ansible.windows.win_file:
        path: '{{ ktuberling_archive_path }}'
        state: absent
      when: not ktuberling_binary.stat.exists

    - ansible.windows.win_shell: |
        $TargetFile = "{{ ktuberling_binary_path }}"
        $ShortcutFile = "{{ ktuberling_shortcut_path }}"
        $WScriptShell = New-Object -ComObject WScript.Shell
        $Shortcut = $WScriptShell.CreateShortcut($ShortcutFile)
        $Shortcut.TargetPath = $TargetFile
        $Shortcut.Save()
      args:
        creates: '{{ ktuberling_shortcut_path }}'
