- hosts: paz
  gather_facts: false
  tasks:
    - ansible.windows.win_get_url:
        url: '{{ gcompris_installer_url }}'
        dest: '{{ gcompris_installer_path }}'

    - ansible.windows.win_package:
        path: '{{ gcompris_installer_path }}'
        state: present

    - ansible.windows.win_file:
        path: '{{ gcompris_installer_path }}'
        state: absent
