- name: Install Temurin JRE
  hosts: paz
  gather_facts: false
  tasks:
    - name: Instalar Temurin JRE
      ansible.windows.win_package:
        path: '{{ temurin_jre_url }}'
        arguments: ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJavaHome,FeatureOracleJavaSoft /quiet
        state: present
