- hosts: paz
  gather_facts: no
  tasks:
    - ansible.windows.win_stat:
        path: '{{ mcpaz_desktop_dir }}'
      register: mcpaz_folder

    - ansible.windows.win_stat:
        path: '{{ mccdp_old_dir }}'
      register: mccdp_folder

    - ansible.builtin.fail:
        msg: Pasta {{ mccdp_old_dir }} nao encontrada para renomear.
      when:
        - not mcpaz_folder.stat.exists
        - not mccdp_folder.stat.exists

    - ansible.windows.win_command: >-
        powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass
        -Command "Rename-Item -Path '{{ mccdp_old_dir }}' -NewName 'mcpaz'"
      when:
        - not mcpaz_folder.stat.exists
        - mccdp_folder.stat.exists
