- hosts: paz
  gather_facts: no
  tasks:
    - win_regedit:
        path: HKLM:\SOFTWARE\Policies\Google\Chrome
        name: NTPShortcuts
        data: '{{ chrome_ntp_shortcuts | to_json }}'
        type: string
