- name: Set Chrome Shortcuts
  hosts: paz
  gather_facts: false
  tasks:
    - ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Google\Chrome
        name: NTPShortcuts
        data: '{{ chrome_ntp_shortcuts | to_json }}'
        type: string
