- hosts: paz
  gather_facts: no
  tasks:
    - ansible.windows.win_get_url:
        url: https://download.kde.org/stable/gcompris/qt/windows/gcompris-qt-26.0-win64-gcc.exe
        dest: C:\Windows\Temp\gcompris-qt-26.0-win64-gcc.exe

    - ansible.windows.win_package:
        path: C:\Windows\Temp\gcompris-qt-26.0-win64-gcc.exe
        arguments: /S
        state: present

    - ansible.windows.win_file:
        path: C:\Windows\Temp\gcompris-qt-26.0-win64-gcc.exe
        state: absent
